### ISSUE TITLE
Can this be used to render really large point clouds?

### ISSUE THREAD

**Issue by SirVer** [eipporko/Cube#5]
I have massive point clouds with 1e9 points and more. Can this tool be used to display these too or is it for small datasets that fit into memory at once?

**Comment by omaralvarez** [comment]
With massive point clouds you will have problems. You would need an out-of-core renderer for that. This project stores all points in memory, so when you exceed RAM or VRAM amounts you will get horrible framerates.

If you are insterested in starting an OSS project that can render massive point clouds contact me. I worked with my University on a project just like that, but they didn't allow me to open source it. I would not mind starting a new project.

https://www.dropbox.com/s/191b3csg807b5y6/tfg_omar_sept2014.pdf?dl=0

**Comment by eipporko** [comment]
Hi @SirVer, 
As @omaralvarez says, this projects only cares about the visualization of the cloud and it was not conceived for manage large amount of points.

**Comment by SirVer** [comment]
Thanks for clarification!

@eipporko My use case is visualizing point clouds, but they are city scale. I was looking for a replacement and ideas to replace tools like leica cyclone.

**Comment by eipporko** [comment]
Maybe you can take a look to the Potree project [github link](https://github.com/potree/potree). It's a webGL solution and seems to work fine with bigger datasets.
